
# wget http://site1368633667.hospedagemdesites.ws/site1.zip

# Dockerfile
# ==================

FROM debian

RUN apt-get update && apt-get install -y apache2 && apt-get clean

ADD site.tar /var/www/html

LABEL description="Apache Webserver 1.0"

VOLUME /var/www/html/

EXPOSE 80


ENTRYPOINT ["/usr/sbin/apachectl"]

CMD ["-D", "FOREGROUND"]


# ======================

# docker image build -t debian-apache:1.0 .

# docker run  -dti -p 80:80 --name meu-apache debian-apache:1.0


