apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: Senha123
            - name: MYSQL_DATABASE
              value: meubanco
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: local
              mountPath: /var/lib/mysql
      volumes:
        - name: local
          PersistentVolumeClaim:
            claimName: local
